version: '2'
services:
  postgres:
    build: ./postgres
    container_name: "postgres"
    volumes:
      - "./scripts:/scripts"
    ports:
      - "5432:5432"
  mysql:
    build: ./mysql
    container_name: "mysql"
    volumes:
      - "./scripts:/scripts"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hogefugapiyo
      - MYSQL_DATABASE=mysql
  client:
    build: ./client
    container_name: "client"
    volumes:
      - "./script:/scripts"
    links:
      - mysql
      - postgres
    tty: true
